### ISSUE TITLE
Socket without using SDK?

### ISSUE THREAD

**Issue by jimbotops** [LivePersonInc/developers-community#114]
I'm trying to create an in-app chat platform but I want full customisation (including sending custom buttons, dropdown boxes etc that will be handled by the native app). For this reason, I don't want to use the SDK.
The Server Chat API looks reasonably good but seems odd to have to constantly poll for things (such as if the agent is typing etc.) which could make it expensive in terms of battery life/data on a mobile device.

Is there a way of opening up a socket for connections without using the SDK?

Thanks

**Comment by donmanguno** [comment]
Hi @jimbotops. Our chat service functions only via a REST API and does not support websocket or anything comparable. 

In terms of battery drain and data usage, we have [a method specifically for checking on the agent's typing status](https://developers.liveperson.com/consumer-experience-server-chat-retrieve-agent-typing-status.html) which returns a very small payload, and [our method for retrieving new chat events](https://developers.liveperson.com/consumer-experience-server-chat-retrieve-chat-events.html)(agent lines, transfers, etc) allows you to pass the `from` parameter so that you only receive new events, limiting the size of the response payload. Because chat is a real-time, synchronous service it is expected that conversations will be relatively short in duration, especially on mobile devices, as the user must be actively engaging with the conversation the entire time.

Our Messaging product (as opposed to Chat) is designed for asynchronous conversations that can remain open for extended periods of time, and it uses the websocket protocol for client - server communication. If Messaging is more suited to your needs than Chat I suggest you speak to your account team (if you have one) or our sales department about it. Be advised, however, that the Messaging API is not yet as well-documented or robust as the Chat API is.

**Comment by donmanguno** [comment]
I think robust was the wrong word. Messaging as a product is production-ready and quite stable, it is merely the API documentation that is quite limited. The API works well--all of our own implementations of Messaging (agent-side, web, in-app) use the same websocket API that we expose to you--but the only well-documented interfaces we have for it are a Node.js SDK and a Javascript SDK.  You can see what documentation we do have for the API [here](https://developers.liveperson.com/agent-int-api-reference.html)

**Comment by donmanguno** [comment]
@jimbotops for more information about Messaging vs Chat I suggest that you talk to your LivePerson account team if you have one, or our Sales team if you don't. I'm going to close this issue now, but if you have any more technical questions about our API's feel free to post them. Thanks.

**Comment by jimbotops** [comment]
Thanks that was really helpful
