### ISSUE TITLE
Javascript API method getEngagement

### ISSUE THREAD

**Issue by nmichaelangelo** [LivePersonInc/developers-community#120]
Javascript API method getEngagement does not return either  "Available" or "Not Available" status.  It takes more than 6 retries for it to return one of the above status.

**Comment by nmichaelangelo** [comment]
This is what I get when it fails.  Notice the object does not have a status property.
Object { time: 1515509166652, message: "Loading account: 61847174, vid: ZmO…", internalCode: 20 }

**Comment by scottwestover** [comment]
@nmichaelangelo If your account has low volume, or is a test account, this is expected behavior. It is recommended that you set the visitor id parameter in the url to the 'vid' value that is returned, and retry the API call 3 times with a 5, 10, and 15 second pause between each request.

You can read more about it here: https://developers.liveperson.com/rt-interactions-create-session.html#response

**Comment by donmanguno** [comment]
Hi @nmichaelangelo, Scott's answer is accurate so I'm going to close this issue. If you have any further problems please open a new issue. Thanks.

**Comment by nmichaelangelo** [comment]
Is it even a good practice to extract vid from a string message?
What happens if some developer at Liveperson decides to change this message string?

{time: 1517227502864, message: "Loading account: 61847174, vid: Q3YzdjMThkNTlkZjk2NDZm", internalCode: 20}
