### ISSUE TITLE
Chat Agent API - PCI Secure Form

### ISSUE THREAD

**Issue by Manegoldsr21** [LivePersonInc/developers-community#125]
Hi, 

Is it possible to use a PCI Secure Form when using the Chat Agent API? We currently have a chat bot that is built out using that API and moving forward we would like to be able to use the Secure Form for certain flows. 

Please let me know if you have any suggestions on how to accomplish this or if I should be asking this question someplace else.

Thanks

**Comment by dvillacis94** [comment]
Hi, 

if you have a User-Type Bot for your bot, then that type is unable to send PCI Secure Forms.

**Comment by Manegoldsr21** [comment]
Our user is type Bot so I had a feeling we wouldn't be able to use it. Do you know if this is something that is looking at being added?

Otherwise do you know if this is something that switching to the Watson Connector would help us get around?

**Comment by donmanguno** [comment]
@Manegoldsr21 Unfortunately the Watson Connector will not enable this functionality. PCI Secure Forms go through a completely independent service in order to isolate that data in a more secure environment and provide the strict access controls that PCI compliance mandates and there is currently no way to allow a bot to interact with that service. This is being considered for addition to the product but I can make no promises nor provide an ETA.

**Comment by Manegoldsr21** [comment]
Sounds good. Thank you for all the information.

**Comment by donmanguno** [comment]
You're welcome
