### ISSUE TITLE
Websocket 503 response

### ISSUE THREAD

**Issue by zuznow** [LivePersonInc/developers-community#127]
Trying the sample https://github.com/LivePersonInc/node-agent-sdk/blob/master/examples/greeting-bot.js

We get 503 when trying the open the WebSocket

**Comment by scottwestover** [comment]
Hi @zuznow, 
Do you know if your account has Messaging enabled? If it isn't, then the 503 is an expected response.

Reference: #49

**Comment by dvillacis94** [comment]
@zuznow can you confirm your account has Messaging enabled?

**Comment by zuznow** [comment]
Messaging was enabled (we do see a bot user, is this enough?) but we still get 503

**Comment by dvillacis94** [comment]
@zuznow you could refer to this [documentation](https://github.com/donmanguno/node-agent-sdk)
under getting started you'll see the pre-requisites needed for your account.

**Comment by zuznow** [comment]
Messaging was enabled, so this works now. Do you know how to make the sample work on Heroku? We need to configure the binding port

**Comment by donmanguno** [comment]
Hi @zuznow.  Heroku requires binding a port for applications that accept incoming network requests, but the Node Agent SDK does not expect or accept any incoming connections. It establishes a single outgoing websocket connection for all communication with our service. As such you need to run the process as a `worker` rather than a `web` process.  To do so add a `Procfile` specifying process type `worker`, i.e. `worker: npm start`. You can see an example [here](https://github.com/LivePersonInc/messaging_bot_samples).

**Comment by zuznow** [comment]
Thanks, now it runs fine, however, could not get my bot to answer a chat request. Tried with the 2 samples, but none of them picks up any conversation. I have the skill "bot" for the live chat windows, and for the bot user. What am I missing?

**Comment by donmanguno** [comment]
Hi @zuznow.  Since your engagement is tied to a skill that tells me that you are probably using a "Live Chat" engagement rather than a "Messaging" one. Try creating a "Messaging" engagement.

![image](https://user-images.githubusercontent.com/10452169/35578650-bb4ef3f6-05b2-11e8-84fb-5e36f0d85dce.png)

Additionally, to ensure that your bot accepts incoming conversations make sure that the bot user has the "Agent" profile (for use with the "agent-bot" example) or the "Agent Manager" profile (for use with the "greeting-bot" example) and can accept more than 0 max messaging conversations.

![image](https://user-images.githubusercontent.com/10452169/35578794-1738cfca-05b3-11e8-81f5-90a28ec2bf20.png)

**Comment by zuznow** [comment]
Thanks for the feedback!

To create a messaging conversation I need an authentication server... also your document says to create a live chat...

Tried to add the agent manager to the greeting bot, nothing change.

I don't see any calls for ExConversationChangeNotification, add debug log and I got only one, when the code start, nothing comes later...

2018-01-30T17:54:37.686979+00:00 app[worker.1]: cqm.ExConversationChangeNotification { subscriptionId: 'df524a0d-4108-45b5-9c90-adde07faa959',
2018-01-30T17:54:37.686983+00:00 app[worker.1]:   changes: [ [length]: 0 ] }

**Comment by donmanguno** [comment]
@zuznow 

Where in the documentation do you see mention of Live Chat? I'll fix that to prevent future misunderstandings.

Yes, our Messaging product requires authentication of some sort (this is the only way to ensure that when your consumers resume their asynchronous conversations later we can present the user with the correct conversation history securely).

You can quickly conduct a messaging conversation on your account using our [Android SDK's Sample Application](https://github.com/LP-Messaging/Android-Messaging-SDK/tree/master/SampleApp-APK).

However, as this is not a code-related issue anymore I suggest that you reach out to our Support department for further assistance in starting Messaging conversations on your account. You can chat with Support from the Connection Panel, which is accessed via the tab on the right edge of LiveEngage:

![image](https://user-images.githubusercontent.com/10452169/35583374-be560884-05bf-11e8-9e26-21f9f8c5ac31.png)
