### ISSUE TITLE
Agent Metrics API - Agent Status and Summary : 400 BAD Request

### ISSUE THREAD

**Issue by ssamaga3** [LivePersonInc/developers-community#143]
Hi Team,

We are successful in getting the DOMAIN from calling the API  'LivePerson Domain API ' through a GET call.

We are passing the Base URI received from the above API response as Domain and the appropriate Account ID as parameters to the Agent Status and Summary methods. 
Here comes the problem. The response that we receive is 400 Bad Request.
Attaching the response captured. Please have a look.

Thanks,
Swathi

[Header Details.txt](https://github.com/LivePersonInc/developers-community/files/1710443/Header.Details.txt)

**Comment by donmanguno** [comment]
Please also provide the request details, including the path and all headers.

**Comment by ssamaga3** [comment]
Hi Team,

Sorry for the delay in response.
Please find the POST request below:

https://va.msghist.liveperson.net/messaging_history/api/account/28084016/agent-view/summary
https://va.msghist.liveperson.net/messaging_history/api/account/28084016/agent-view/status

[Request Details.docx](https://github.com/LivePersonInc/developers-community/files/1722730/Request.Details.docx)

Thanks,
Swathi

**Comment by ssamaga3** [comment]
Hi Team,

Any Updates on this?
We are really stuck here. Any guidance/inputs will be helpful.

Thanks,
Swathi

**Comment by donmanguno** [comment]
Hi @ssamaga3 the document you shared seems to contain the response headers again. I was interested in the _request_ headers specifically.

The error you're getting indicates an authentication issue. Ensure that you are creating a signed oAuth header using your appkey, secret, access token, and access token secret, and that you're putting it in your request's headers rather than passing it as a querystring parameter.  I was able to make this request on your account without issue.

![image](https://user-images.githubusercontent.com/10452169/36276886-3c97df52-125d-11e8-9424-702016eef552.png)

**Comment by ssamaga3** [comment]
Hi Donmanguno,

We now attempted oAuth 1.0 auth. We are receiving this error response
{"code":"0013","debugMessage":"Invalid json format"}

We haven't passed any parameters in Request body.

Attaching the request header. Please let us know the steps to fetch the request header if this is not the one.

[Request Header.txt](https://github.com/LivePersonInc/developers-community/files/1739566/Request.Header.txt)

Thanks,
Swathi

**Comment by donmanguno** [comment]
Send an empty `{}` as the body of your request if you don't plan to use any body parameters.

**Comment by ssamaga3** [comment]
Hi Donmanguno.

This helped us. Thanks for understanding we are new to this. 

Thanks,
Swathi
