### ISSUE TITLE
FAB Button Display for new conversations

### ISSUE THREAD

**Issue by pramodalapati** [LivePersonInc/developers-community#149]
I am using a hybrid application with Liveperson integrated into it. I have a call being made to the checkActiveConversation method. Ideally this method should return a true/false value based on the state of the conversation. However this method call doesn't return the actual value (returns false by default) unless the Chat Window in opened in the App. Is there a way to get the actual state of the conversation (true/false) without having to open the chat window? Please note that this method is being called after SDK Initialization.

**Comment by dvillacis94** [comment]
Hi @pramodalapati,

We can confirm this is working on the SDK (3.0), even if the user is not in the Messaging Screen, it return the correct values.

- Which version of the SDK are you using?

**Comment by pramodalapati** [comment]
We are using 2.9.3 for iOs and 2.9.2 for Android

**Comment by dvillacis94** [comment]
Hi @pramodalapati,

We can confirm this is working on the SDK 2.9.3 for iOs and 2.9.2 for Android, even if the user is not in the Messaging Screen, it return the correct values.

**Comment by dvillacis94** [comment]
Hi @pramodalapati,

After Reviewing your logs,

When you're checking if the Conversation is active, you get false, because the Conversation was closed as you can see on the next log lines:

```
state = Optional("CLOSE"),
closeReason = Optional("CONSUMER"),
startTs = Optional(2018-02-23 04:31:29 +0000),
endTs = Optional(2018-02-23 04:33:59 +0000),
```

Later you start a new Conversation and you received a true, in that moment the Conversation was active, even if you are not on the Conversation Screen

`2018-02-23 14:56:41.518349+0530 Kundencenter[3094:1809948] check_active_conversation success callback ..true`

**Comment by orenkatz** [comment]
Hey @pramodalapati,
Did @dvillacis94 insights helped with the issue you were experiencing?

**Comment by dvillacis94** [comment]
Hi @pramodalapati.

I'm closing this issue, if you have any more questions related to this feel free to reopen it, or create a new one for any new issues.
