### ISSUE TITLE
Token response {"internalErrorCode":"9007"} /api/account/90155041/app/default/authenticate?v=2.0

### ISSUE THREAD

**Issue by VatslauX** [LivePersonInc/developers-community#198]
/api/account/90155041/app/default/authenticate?v=2.0
500 ERROR
{"internalErrorCode":"9007"} 

Please could You write the list of errors and cases
If it`s in doc - just link
Thanks in advance

**Comment by dvillacis94** [comment]
Hi @VatslauX,

That one is related to the jwt not being valid, could you share the request headers you're using?

**Comment by shaymLP** [comment]
@VatslauX, The team is looking into your request. We will respond as soon as possible.

**Comment by VatslauX** [comment]
Thank You

**Comment by shaymLP** [comment]
@VatslauX You can view the list of error codes here: https://docs.google.com/document/d/1SXzXgCTEjztbDij7OwOPaieWJeSb8bFSncTXsw843cw/edit?usp=sharing
9007 is "CUSTOMER_JWT_NOT_VALID - failed to validate customer JWT - mostly due to public key doesn't match customer private key ( in the connector config)"
