### ISSUE TITLE
Android SDK: Push notifications no longer have a click action on v3.1

### ISSUE THREAD

**Issue by bramley-stride** [LivePersonInc/developers-community#210]
Clicking on a LP notification no longer does anything as of SDK v3.1. Previously, it used to open the chat window (until v3.0, when it crashed instead - see issue #157 )

**Comment by bramley-stride** [comment]
The method `com.liveperson.infra.handler.NotificationHandler.createPendingIntent()` is no longer referenced.

**Comment by shaymLP** [comment]
The flow you described is expected behavior as from version 3.1 using the following function : LivePerson.handlePushMessage(this, remoteMessage.getData(), account, **true**);  will only display the push message and the message **will not** be click-able, best practice will be setting the above flag to false and handling the message by the host app fully. We do plan to add back that functionality in the future.

**Comment by bramley-stride** [comment]
OK, this change wasn't in the release notes at https://developers.liveperson.com/consumer-experience-android-sdk-release-notes.html , was it flagged somewhere else?
