### ISSUE TITLE
oauth docs are woefully not up to date

### ISSUE THREAD

**Issue by Kadell** [LivePersonInc/developers-community#27]
I would suggest a overall check but here are some of the things I know are wrong or bad:

No code flow for WEB diagram (elena has one)
Page 3 shows the checkmark in the wrong place in the info widget
No indication that despite not needing certain parameters you must fill in the ui with something to submit the config. 
Example on page 18 doesn't include personal info section of sdes or indicate any of the properties of said vars.

No indications of what ui elements are required to be filled in depending on which implementation you are using:
web - codeflow v implicit & embedded v popout
sdk - codeflow v implicit

I feel like shmulik fixed some things awhile ago, but these still persist.

**Comment by EdenKupe** [comment]
Hey,

Thanks for opening this issue. I agree wholeheartedly; the entire document if out of date. The idea with publishing it was together exactly this info, since the process of updating it was going slowly. I will forward all the info you included here to Shmulik, Munir and Barber and they will work on updating the document.

**Comment by EdenKupe** [comment]
Communication continued via email, closing this issue for now.
