### ISSUE TITLE
Authentication not clear on certain steps

### ISSUE THREAD

**Issue by gitLee47** [LivePersonInc/developers-community#346]
Hello,
I was trying to create a POC and reached the point where I get a POST call to my token endpoint with:code, grant_type and redirect_uri. I perform the OPENID JWT encryption and signing and then return it back as a 200. Still the developer console shows 401 unauthorized and defaults to the survey:
{"error":{"time":"2019-07-10T19:30:16.887-04:00","message":"Failed to validate user with customer authentication service","internalCode":10}}

I had a few questions as the document seem unclear:
1. in the token what is **iss** specifically? Is this supposed to be the token auth service domain that I specified in the LivePerson authorization configuration dialog or something else?
2. For signing the token do I need to use the "—–BEGIN PRIVATE KEY—–" & "—–END PRIVATE KEY—–"  header and tail or just the key.
3. in the doc there is this line: JWE header should include header name “alg" with the value: RSA_OAEP_256.
What is JWE header? Is that a typo? Are you talking about a http response header with key and value as that or to use JWT SignOptions?

I am using NodeJs in my auth service

**Comment by EdenKupe** [comment]
Hey!

Sorry for the delay here. Let me answer your questions:

1) As detailed in the docs, the `iss` is "The name of the Authorization Service as configured in LivePerson." So that is indeed the service domain that you specified in the LP configuration.

2) The key without the header and tail.

3) JWE is an industry standard. Here is the [RFC](https://tools.ietf.org/html/rfc7516) and [here](https://tools.ietf.org/html/rfc7516#section-4.1.1) is the part where it talks about the `alg` header

Thanks!
