### ISSUE TITLE
Additional visitor data using Messaging Window API

### ISSUE THREAD

**Issue by sciesielski** [LivePersonInc/developers-community#39]
According to https://developers.liveperson.com/consumer-int-authentication.html I can add to JWT object additional information like "name": "Eitan". How can I make it visible in LiveEnagage chat window?

**Comment by EdenKupe** [comment]
Hey,

Thanks for opening an issue. @eitan101, could you please provide more insight!

**Comment by sciesielski** [comment]
Hello,

@eitan101, could you provide any information about taking visitor information from JWT? Is it possible?

**Comment by scottwestover** [comment]
@sciesielski 

To have the additional information show up in the LiveEngage chat window, the information has to be passed as one of the variables that are supported in the standard claim or custom claim sets here: https://developers.liveperson.com/guides-authentication-detailedapi.html

Instead of using "name": "Eitan", I would use "given_name": "Eitan", to have the name populate properly.

<img width="384" alt="2017-10-24_1131" src="https://user-images.githubusercontent.com/9931822/31952580-ee51e674-b8ae-11e7-9ced-e529fa7d8ddb.png">

@EdenKupe Is it possible to have the tutorial updated to use one of the values in the standard claim set?

**Comment by EdenKupe** [comment]
Hey,

I've changed the value and added a note referring to the specific part of the Authentication document which lists the correct values.

Thanks!

**Comment by scottwestover** [comment]
@EdenKupe Thanks!
