### ISSUE TITLE
Messaging Window APIs: GetClock()

### ISSUE THREAD

**Issue by marcodagolini** [LivePersonInc/developers-community#80]
Hello Team!

I'm using the GetClock() method and i'm receiving a 200 from the server.
Here below what i see in my Chrome developer tool:

![screen shot 2017-11-26 at 18 08 17](https://user-images.githubusercontent.com/22427475/33242711-5f3731fc-d2d9-11e7-919e-4dce515e9e3b.png)

I can see also the call list every 10 secs:

![screen shot 2017-11-26 at 18 38 20](https://user-images.githubusercontent.com/22427475/33242723-801bdea4-d2d9-11e7-92fa-1e6f27905aff.png)

Despite this, the WSS connection is closed after 60 secs, here below the evt:

![screen shot 2017-11-26 at 18 29 46](https://user-images.githubusercontent.com/22427475/33242741-bb3b7710-d2d9-11e7-961b-192d11e563b1.png)

Any clue why?
Thank you in advance for your kind support!

Marco

**Comment by donmanguno** [comment]
Hi Marco,
Regarding the second screenshot: those are Shark requests which occur because you have the lpTag on your page. They are unrelated to the websocket connection.
Do you send the getClock method periodically, or only once when you connect?
I am looking into close reason 1006 to see if I can clarify what exactly it means.

**Comment by marcodagolini** [comment]
Hello Mark!

I was calling getClock method only once.
I tried to call this method inside one setInterval(), this is working like a charm!

Thank you again!

Marco
