### ISSUE TITLE
Programmatically determine if call center is open

### ISSUE THREAD

**Issue by pmparis** [LivePersonInc/developers-community#81]
We have a custom button that invokes the chat window based on the lpTag object.  Is there a way that I can determine if the call center is open or not via your objects or api, so that I can hide this custom button?

**Comment by donmanguno** [comment]
Hi @pmparis does this question relate to chat or messaging? For chat you can use the [Server Chat API](https://developers.liveperson.com/consumer-experience-server-chat-getting-started.html)'s Retrieve Availability, Retrieve Available Slots, or Retrieve Estimated Wait Time methods.

We don't have any equivalent methods for checking Messaging agent availability because Messaging's asynchronous nature means that offline messages are expected. It's possible to set an entire messaging account to "Offline" in the UI in order to present a corresponding message to consumers who try to contact you, but our API currently doesn't support getting or setting this value.
